### ISSUE TITLE
calico-policy-controller is pending and get nodes shows no resources found

### ISSUE THREAD

**Issue by ivanfetch** [kelseyhightower/kubeadm-single-node-cluster#2]
I am using your slightly adapted startup.sh script in a Ubuntu 17.04 instance running on AWS. I find that the calico-policy-controller pod shows pending, and `get nodes` shows that no resources are found. I'm not sure whether the few adjustments I've made for AWS are causing this to break, or what else I might be missing.

My hostname does not exist in DNS, but I added a fully qualified entry to /etc/hosts using the internal AWS IP of my instance.

I tried adding this to kubeadm.conf per the Calico docs about the pod subnet, with the same result:
```
networking:
  podSubnet: 192.168.0.0/16
```

I changed the `cloudProvider` in kubeadm.conf to `aws` and the `Environment="KUBELET_EXTRA_ARGS=--cloud-provider=aws"` in the systemd drop-in.

I am using my instance internal IP, but no external one, in place of the `curl` to Google Compute metadata.

Here is what I'm seeing:

```
# kubectl get pods --all-namespaces
NAMESPACE     NAME                                                 READY     STATUS    RESTARTS   AGE
kube-system   calico-policy-controller-1727037546-rbk5b            0/1       Pending   0          10m
kube-system   etcd-standalone.local                      1/1       Running   1          20s
kube-system   kube-apiserver-standalone.local            1/1       Running   1          20s
kube-system   kube-controller-manager-standalone.local   1/1       Running   1          20s
kube-system   kube-dns-2425271678-vx0bx                            0/3       Pending   0          10m
kube-system   kube-scheduler-standalone.local            1/1       Running   1          20s
```

```
# kubectl get nodes
No resources found.
```

Thank you for your awesome work on Kubernetes - presentations, examples and demos, Etc!

**Comment by kelseyhightower** [comment]
@ivanfetch I don't have the bandwidth to troubleshoot this in AWS. I'm going to add a disclaimer that this is only tested in GCE, but could be used in other environments with some work. I really want to keep this super simple. Each cloud provider has slight differences that it would take a lot of time to account for them.
